# name of workflow
name: Publish Unpackaged EXE

# triggers
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# what to do
jobs:
  build:
    runs-on: windows-latest
    
    # values for the build
    env:
      Configuration: Release
      RID: win-x64

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1.3

    # restore the project
    - name: Restore the project
      run: msbuild "Windows Diagnostic Tools.csproj" /t:Restore /p:Configuration=$env:Configuration /p:RuntimeIdentifier=$env:RID

    # create the app (self-contained)
    - name: Create the app (Self-Contained)
      run: msbuild "Windows Diagnostic Tools.csproj" /t:Publish /p:Configuration=$env:Configuration /p:RuntimeIdentifier=$env:RID /p:WindowsAppSDKSelfContained=true /p:WindowsPackageType=None /p:EnableMsixTooling=true /p:PublishDir=./publish/$env:RID/

    # upload the app
    - name: Upload app
      uses: actions/upload-artifact@v4
      with:
        name: Unpackaged-EXE-x64
        path: ./publish/win-x64/