# name of workflow
name: Publish Unpackaged EXE

# triggers
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# what to do
jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]
        platform: [x64, x86]

    runs-on: windows-latest
 
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # install .NET 8.0 (project targets .NET 8.0)
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1.3

    # create the app by building the project file with msbuild
    - name: Create the app (Self-Contained)
      run: msbuild "Windows Diagnostic Tools.csproj" /t:Publish /p:Configuration=$env:Configuration /p:Platform=$env:Platform /p:WindowsAppSDKSelfContained=true /p:WindowsPackageType=None /p:PublishDir=./publish/${{ matrix.platform }}/
      env:
        Configuration: ${{ matrix.configuration }}
        Platform: ${{ matrix.platform }}

    # upload it
    - name: Upload app
      uses: actions/upload-artifact@v4
      with:
        name: Unpackaged-EXE-${{ matrix.platform }}
        path: ./publish/${{ matrix.platform }}/